### ISSUE TITLE
Security flaw

### ISSUE THREAD

**Issue by christianmalek** [simpaddock/pitlane#1]
See https://github.com/simpaddock/pitlane/blob/3cfd854f4e1a1a238b2c2e1ef7743848cf381375/frontend/views.py#L417

If you're refering to the following `safe=False` from `JsonResponse`: No, it's not. See https://docs.djangoproject.com/en/2.1/ref/request-response/#jsonresponse-objects

There's written:
> Before the 5th edition of ECMAScript it was possible to poison the JavaScript Array constructor. For this reason, Django does not allow passing non-dict objects to the JsonResponse constructor by default. However, most modern browsers implement EcmaScript 5 which removes this attack vector. Therefore it is possible to disable this security precaution.

**Comment by cmllr** [comment]
Thanks for clarification!
